table_name: CREDIT_LOAN
columns:
  - name: client_nr
    type : INTEGER
  - name: yearmonth
    type : INTEGER
  - name: credit_application
    type : inINTEGERt64
  - name: nr_credit_applications
    type : INTEGER
  - name: total_nr_trx
    type : INTEGER
  - name: nr_debit_trx
    type : INTEGER
  - name: volume_debit_trx
    type : INTEGER
  - name: nr_credit_trx
    type : INTEGER
  - name: volume_credit_trx
    type : INTEGER
  - name: min_balance
    type : INTEGER
  - name: max_balance
    type : INTEGER
  - name: CRG
    type : FLOAT

